# Generated by Django 4.2.5 on 2024-03-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=50)),
                ('sname', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=55)),
                ('password', models.CharField(max_length=55)),
                ('mno', models.CharField(max_length=11)),
            ],
        ),
    ]
