# Generated by Django 4.2.5 on 2024-03-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
                ('user_phone', models.CharField(max_length=50)),
                ('user_location', models.CharField(default='Unknown', max_length=50)),
                ('user_profile', models.ImageField(upload_to='images/user')),
                ('status', models.CharField(default='Accepted', max_length=15)),
            ],
            options={
                'db_table': 'User_details',
            },
        ),
    ]
